# Generated by Django 5.0.6 on 2024-07-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOTEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
