# Generated by Django 5.0.6 on 2024-07-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotevent',
            options={'verbose_name': 'IOT Event'},
        ),
    ]
